// <auto-generated />
namespace MVC_CRUDE_API_TASK2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class clr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clr));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280328464_clr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
